# Generated by Django 5.2.7 on 2025-10-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_youtubelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='youtubeid',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
